In [2]:
from sklearn.decomposition import PCA

In [3]:
mat = [[1, 3], [4, 2]]

In [5]:
p = PCA(n_components=2)
p.fit(mat)

PCA(n_components=2)

In [6]:
p.explained_variance_

array([5.00000000e+00, 2.77333912e-33])

In [1]:
import numpy as np
from numpy.linalg import eig

In [10]:
A = np.array([[2, 6], [5, 1]]).T
A

array([[2, 5],
       [6, 1]])

In [12]:
M = np.mean(A.T, axis=1)
M

array([4., 3.])

In [13]:
C = A - M
C

array([[-2.,  2.],
       [ 2., -2.]])

In [15]:
V = np.cov(C.T)
V

array([[ 8., -8.],
       [-8.,  8.]])

In [16]:
values, vectors = eig(V)

In [17]:
values, vectors

(array([1.60000000e+01, 1.77635684e-15]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [18]:
Y = np.dot(vectors.T, C)
Y

array([[-2.82842712e+00,  2.82842712e+00],
       [ 4.44089210e-16, -4.44089210e-16]])

In [20]:
(np.dot(vectors, Y) + M).T

array([[2., 6.],
       [5., 1.]])